[package]
name = "messlatte-ensemble"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
messlatte-units = { path = "../units" }
messlatte-formats = { path = "../formats" }
messlatte-method-frogcrab = { path = "../methods/frogcrab" }

[lints]
workspace = true
