[package]
name = "messlatte"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
messlatte-units = { path = "../units" }
messlatte-formats = { path = "../formats" }
messlatte-generator = { path = "../generator" }
messlatte-method-frogcrab = { path = "../methods/frogcrab" }
messlatte-scoring = { path = "../scoring" }
messlatte-ensemble = { path = "../ensemble" }

[lints]
workspace = true
